<?php
/**
 * @file
 * Main file for the Bootstrap block module
 */

/**
 * Implements hook_permission().
 */
function sm_btb_permission() {
  return array(
    'administer bootstrap block' => array(
      'title' => t('Administer Bootstrap block'),
      'description' => t('Set settings for Bootstrap block'),
    ),
  );
}


/**
 * Implements theme_preprocess_block().
 *
 * Extend block's classes with any user defined classes.
 */
function sm_btb_preprocess_block(&$vars) {
  $block = $vars['block'];
  if (isset($block->css_class) && $block->css_class != '') {
    $vars['classes_array'] = array_merge($vars['classes_array'], explode(' ', $block->css_class));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Alter block edit form to add configuration field.
 */
function block_class_form_alter(&$form, &$form_state, $form_id) {
  if (user_access('administer bootstrap block') && ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form')) {
    // Load statically cached block object used to display the form.
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    $form['settings']['button'] = array(
      '#type' => 'textfield',
      '#title' => t('Button text'),
      '#default_value' => isset($block->css_class) ? $block->css_class : '',
      '#description' => t('Add button text for bootstrap  modal link.'),
      '#maxlength' => 255,
    );

    $form['#submit'][] = 'block_class_form_submit';
  }
}